### ISSUE TITLE
Não funciona a partir da segunda página

### ISSUE THREAD

**Issue by luizclaudio98** [natenho/chromercadolivre#1]
Quando se passa para a próxima página de uma pesquisa, a extensão para de funcionar. As vezes não funciona nem na primeira página.
![Captura de Tela (1)](https://user-images.githubusercontent.com/54826550/76241546-ea1ea900-6213-11ea-822d-9b372a5ffea6.png)
![Captura de Tela (7)](https://user-images.githubusercontent.com/54826550/76241553-eb4fd600-6213-11ea-9712-8d9480041595.png)

**Comment by natenho** [comment]
Olá! Tudo bem? Vou investigar o que pode ter ocorrido. Muito obrigado pelo
seu contato, me estimula a evoluir esse trabalho pra ficar melhor.

Abraços,

**Comment by natenho** [comment]
@luizclaudio98 , acredito que o problema tenha sido resolvido. É necessário alguns dias para que o Google publique a nova versão corrigida, ok? Mais uma vez, obrigado pelo interesse.
